version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
      - API_BASE_URL=${API_BASE_URL}
      - MENU_NAME=${MENU_NAME}
      - SITE_NAME=${SITE_NAME}
    volumes:
      - .:/app
    container_name: flask_app
    
