swagger: "2.0"
info:
  title: "Taffa Menu API"
  description: "API for retrieving restaurant menus in different formats."
  version: "1.0.0"
paths:
  /taffa/{language}/today/:
    get:
      summary: "Get today's menu in text format"
      parameters:
        - name: language
          in: path
          required: true
          type: string
      responses:
        200:
          description: "Today's menu in plain text"
          schema:
            type: string
  /taffa/{language}/week/:
    get:
      summary: "Get weekly menu in text format"
      parameters:
        - name: language
          in: path
          required: true
          type: string
      responses:
        200:
          description: "Weekly menu in plain text"
          schema:
            type: string
  /taffa/{language}/{days}/:
    get:
      summary: "Get menu in X days in text format"
      parameters:
        - name: language
          in: path
          required: true
          type: string
        - name: days
          in: path
          required: true
          type: integer
          description: "Number of days ahead (0 = today)"
      responses:
        200:
          description: "Menu in X days in plain text"
          schema:
            type: string
  /taffa/{language}/json/today/:
    get:
      summary: "Get today's menu in JSON format"
      parameters:
        - name: language
          in: path
          required: true
          type: string
      responses:
        200:
          description: "Today's menu in JSON"
          schema:
            type: object
  /taffa/{language}/json/week/:
    get:
      summary: "Get weekly menu in JSON format"
      parameters:
        - name: language
          in: path
          required: true
          type: string
      responses:
        200:
          description: "Weekly menu in JSON"
          schema:
            type: array
            items:
              type: object
  /taffa/{language}/json/{days}/:
    get:
      summary: "Get menu in X days in JSON format"
      parameters:
        - name: language
          in: path
          required: true
          type: string
        - name: days
          in: path
          required: true
          type: integer
          description: "Number of days ahead (0 = today)"
      responses:
        200:
          description: "Menu in X days in JSON"
          schema:
            type: object
  /taffa/{language}/html/today/:
    get:
      summary: "Get today's menu in HTML format"
      parameters:
        - name: language
          in: path
          required: true
          type: string
      responses:
        200:
          description: "Today's menu in HTML"
          schema:
            type: string
  /taffa/{language}/html/week/:
    get:
      summary: "Get weekly menu in HTML format"
      parameters:
        - name: language
          in: path
          required: true
          type: string
      responses:
        200:
          description: "Weekly menu in HTML"
          schema:
            type: string
  /taffa/{language}/html/{days}/:
    get:
      summary: "Get menu in X days in HTML format"
      parameters:
        - name: language
          in: path
          required: true
          type: string
        - name: days
          in: path
          required: true
          type: integer
          description: "Number of days ahead (0 = today)"
      responses:
        200:
          description: "Menu in X days in HTML"
          schema:
            type: string
