swagger: "2.0"
info:
  title: Taffa Menu API
  description: API to fetch and display menu information in different formats.
  version: "1.0.0"

host: localhost:5000
schemes:
  - http
basePath: /

paths:
  /:
    get:
      summary: Home
      description: Returns a welcome message.
      produces:
        - text/plain
      responses:
        200:
          description: Success
          schema:
            type: string
            example: "Welcome to the home page!"

  /taffa/{language}/today/:
    get:
      summary: Get today's menu (text)
      description: Fetches the menu for today in plain text format.
      parameters:
        - name: language
          in: path
          required: true
          type: string
          enum: [en, sv, fi]
          description: Language code (en = English, sv = Swedish, fi = Finnish)
      produces:
        - text/plain
      responses:
        200:
          description: Success
          schema:
            type: string
            example: "Option 1: Pasta Bolognese\nOption 2: Vegetarian Curry"

  /taffa/{language}/json/{days}/:
    get:
      summary: Get menu as JSON
      description: Fetches the menu for the specified number of days in JSON format.
      parameters:
        - name: language
          in: path
          required: true
          type: string
          enum: [en, sv, fi]
          description: Language code (en = English, sv = Swedish, fi = Finnish)
        - name: days
          in: path
          required: true
          type: integer
          minimum: 0
          description: Number of days in the future for which to retrieve the menu.
      produces:
        - application/json
      responses:
        200:
          description: JSON menu response
          schema:
            type: object
            properties:
              day:
                type: string
                example: "2025-03-19"
              dayName:
                type: string
                example: "Wednesday"
              Option 1:
                type: string
                example: "Pasta Bolognese"
              Extra:
                type: string
                example: "Fruit Salad"

  /taffa/{language}/{days}/:
    get:
      summary: Get menu as text
      description: Fetches the menu for the specified number of days in plain text format.
      parameters:
        - name: language
          in: path
          required: true
          type: string
          enum: [en, sv, fi]
          description: Language code (en = English, sv = Swedish, fi = Finnish)
        - name: days
          in: path
          required: true
          type: integer
          minimum: 0
          description: Number of days in the future for which to retrieve the menu.
      produces:
        - text/plain
      responses:
        200:
          description: Success
          schema:
            type: string
            example: "Option 1: Pasta Bolognese\nOption 2: Vegetarian Curry"
